### ISSUE TITLE
[BF] OFX Import errors

### ISSUE THREAD

**Issue by ouafnico** [lyskouski/app-finance#518] opened 2024-11-26 16:17 UTC
**Describe the bug**
I'm trying to import some ofx, but I got errors.

**To Reproduce**
1. Go to Metrics / import
2. Click on pick ofx file
3. Choose the file and validate

**Screenshots**
![image](https://github.com/user-attachments/assets/f5da46f0-97af-4119-ade5-3c0bf033eb0c)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser : brave
 
**Additional context**
App self-hosted on Debian/Nginx

I can maybe provide some anonymous ofx starting data.
If I try to change the /STATUS by /SEVERITY, I will have some more errors.
Is it a problem with my bank provided ofx ?

**Comment by lyskouski** [comment] 2024-11-26 16:45
Hello @ouafnico,

You may share OFX file via support@tercad.pl. But from the first view it looks like a corrupted file: OFX is a XML based file, and closed SEVERITY tag is missing there.

**Comment by ouafnico** [comment] 2024-11-26 17:33
I will provide you the beginning of the file by mail, but I guess I will never be able to ask my bank to correct the file...
I'm using it correctly on other softwares.

**Comment by ouafnico** [comment] 2024-11-26 17:39
Great, I see this by mail :) If I can help

**Comment by lyskouski** [comment] 2024-11-28 08:35
Hello @ouafnico ,
Fixed in version 5.9.0 (https://github.com/lyskouski/app-finance/releases/tag/v5.9.0)

**Comment by ouafnico** [comment] 2024-11-28 09:01
> Hello @ouafnico , Fixed in version 5.9.0 (https://github.com/lyskouski/app-finance/releases/tag/v5.9.0)

Thanks !

I don't have the error anymore, but got this : 
![image](https://github.com/user-attachments/assets/ede33c6f-9db1-4fba-9c18-655bcde62533)


Transactions seems imported, but all with 0.00 value.

**Comment by lyskouski** [comment] 2024-11-28 09:06
Sorry, @ouafnico, may you share some more samples? With provided record it was parsed correctly.

![image](https://github.com/user-attachments/assets/9e8bfe57-efee-4408-8704-f11ce8206c87)

**Comment by ouafnico** [comment] 2024-11-28 09:16
> Sorry, @ouafnico, may you share some more samples? With provided record it was parsed correctly.
> 
> ![image](https://private-user-images.githubusercontent.com/8281925/390713844-9e8bfe57-efee-4408-8704-f11ce8206c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODU2NjYsIm5iZiI6MTczMjc4NTM2NiwicGF0aCI6Ii84MjgxOTI1LzM5MDcxMzg0NC05ZThiZmU1Ny1lZmVlLTQ0MDgtODcwNC1mMTFjZTgyMDZjODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMDkxNjA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjEzZTlkODNlMWNmYjBmMDY5ZWM4NDliZWVjY2E5MDJkMmM0Y2U1ZWM4OWJlMTczOWRhNjMyMDM2YTUyM2YxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Tbi6VOEMHCNaCbJtv4lVW-5MohQSHv5nRWI0zSkfKYA)
> 
> Btw, next import should override corrupted data, since it's used ID from OFX records.

Ok I see what I can send you by email

**Comment by lyskouski** [comment] 2024-11-28 09:28
> Where is stored the data of the app locally ?
For web-version it's Indexed DB ([F12] - Storage - Indexed DB)

> Now I see it in the list for the mapping during the import, but I can't select the account.
It's a valuable point, thanks for highlighting. Account is definitely has to be shown in the form to be set.

**Comment by lyskouski** [comment] 2024-11-28 09:32
Just checked, account is shown near the end of the form "Default value for  'Account: Title'"

![image](https://github.com/user-attachments/assets/a5c9648f-f5b9-4f49-a0f2-0ba825cbae00)

**Comment by ouafnico** [comment] 2024-11-28 09:42
Account is created "as bank account".
Where is localy the file on the server (if I want to trash/purge all data)

On default account, I can click and see the number of the account, but it's not holding.

![image](https://github.com/user-attachments/assets/0951e05c-50a1-41b4-aa2f-4b0e37b9face)

**Comment by lyskouski** [comment] 2024-11-28 10:10
> Where is localy the file on the server (if I want to trash/purge all data)

For Web-version it's not stored anywhere on the server. Press [F12] to open developer console, find the tab "Storage" (in additional scope), from the left bar choose "Indexed DB", by right click on the site url choose "Delete all"

If we're talking about desktop apps - [Documents]/.terCAD/app-finance.log

**Comment by lyskouski** [comment] 2024-11-28 10:23
> On default account, I can click and see the number of the account, but it's not holding.

Identified the bug, have to fix it.

**Comment by lyskouski** [comment] 2024-11-28 11:01
Fix is pushed to the main branch, you may either build app from sources or wait for 5.9.1 release

**Comment by ouafnico** [comment] 2024-11-28 12:51
> > Where is localy the file on the server (if I want to trash/purge all data)
> 
> For Web-version it's not stored anywhere on the server. Press [F12] to open developer console, find the tab "Storage" (in additional scope), from the left bar choose "Indexed DB", by right click on the site url choose "Delete all"
> 
> If we're talking about desktop apps - [Documents]/.terCAD/app-finance.log

No way to have a internal database for web version ?

I will test the 5.9.1, thanks ;)

**Comment by lyskouski** [comment] 2024-11-28 13:07
> No way to have a internal database for web version ?

Indexed DB is the internal database for the web version

> I will test the 5.9.1

@ouafnico , may you send samples of OFX that has failed on your side? That will help to find out the cause of errors and zero-values. After that fix I'll release a new version. Thanks

**Comment by ouafnico** [comment] 2024-11-28 13:17
By internal I mean on the web server filesystem (not on the client).
Zero values seems fixed, I guess bad manipulation on my part ; but I will send you samples

**Comment by lyskouski** [comment] 2024-11-28 13:28
> By internal I mean on the web server filesystem (not on the client)

It was not designed that way, also according to the privacy policy the user has full ownership and control of their data; nothing but a few metrics (Google Analytics: action type, location, language) are sent off-site (as to the web server filesystem). But for your own purposes you may change that behavior by changing https://github.com/lyskouski/app-finance/blob/main/lib/_classes/storage/transaction_log/abstract_storage_web.dart .

**Comment by lyskouski** [comment] 2024-11-28 14:24
https://github.com/lyskouski/app-finance/releases/tag/v5.9.1
@ouafnico, version 5.9.1 with the fix for selectors is released, please, check. Thanks

**Comment by lyskouski** [comment] 2024-12-02 07:50
Dear @ouafnico,
Problem seems solved, if you find anything else, feel free to contact. Thank you very much for identifying the problems.

**Closed by lyskouski** 2024-12-02 07:50 UTC
Labels: bug
