### ISSUE TITLE
[CR] Floating point limitation in the currency exchange

### ISSUE THREAD

**Issue by Igortorrente** [lyskouski/app-finance#529] opened 2024-12-09 22:18 UTC
**Describe the bug**
The app doesn't have enough float point precision to accept values too little of conversion. For example when the differences between the currencies are 1:10200 (or 0,0000980392) I can't input the number in the conversion field when adding a expense in the credit card.

**To Reproduce**
1. In the home click in '+'
2. Select expense
3. Select an credit card
4. Add 200 in the 'Amount of Expenses'
5. Try to add the conversion rate like 0,0000980392

**Expected behavior**
I expect to be able to tipe the number or paste it.

**Desktop (please complete the following information):**
 - OS: Flatpak app
 - Version 6.0.0 build 1754

**Comment by lyskouski** [comment] 2024-12-10 10:00
Dear @Igortorrente,
Thanks for highlighting the problem.

It was set a limitation in decimals for the final amount that leads to the cut of conversion rate.

Improved to allow the lower rating value.

**Comment by lyskouski** [comment] 2024-12-10 10:07
Please, check the fix in 6.0.1 version.

**Comment by Igortorrente** [comment] 2024-12-10 11:45
Hi @lyskouski, No I can input the value, Thanks! But it doesn't seem to save. When I go back the specific expense the 'conversion' and 'taken in USD' continue with 0.

**Comment by lyskouski** [comment] 2024-12-10 12:54
Hello @Igortorrente,
May you clarify a little bit your steps? Where are you stuck on? 

Conversion rate is saved simultaneously with the bill. As an example, adding bill ("[+]" from Home page):
![image](https://github.com/user-attachments/assets/5d90abd8-06f7-4a52-b8fa-7f74e9c6bc6c)
will lead to the next exchange rate saved (Menu > Currencies):
![image](https://github.com/user-attachments/assets/a3bdcdcb-4d57-49ba-be6c-f0361d50dd9d)
next call for a new bill ("[+]" from Home page):
![image](https://github.com/user-attachments/assets/888f944b-39fc-476d-a328-a54ac9fcef3d)

**Comment by Igortorrente** [comment] 2024-12-10 13:06
Yeah, it works for a new expense. But doesn't work when updating an old one

**Comment by lyskouski** [comment] 2024-12-10 13:52
Thanks, @Igortorrente. This was another issue identified, which was that the exchange was not saving during the edit expense action. Fixed in version 6.0.2.

**Comment by lyskouski** [comment] 2024-12-10 14:18
With that case it was also identified the problem with totals... will definitely fix it. Short-term solution is to delete expense and add it again.

![image](https://github.com/user-attachments/assets/8af127ea-9127-4168-89e1-c9840a773521)

**Comment by Igortorrente** [comment] 2024-12-10 21:13
Now it's working! Thanks @lyskouski !

**Comment by Igortorrente** [comment] 2024-12-11 01:35
This Math is no quite right
![imagen](https://github.com/user-attachments/assets/f2c7f08d-de96-4980-8e70-532125fcdeca)

![imagen](https://github.com/user-attachments/assets/abfa0a4b-117c-4c7e-89e2-ad5861478f5e)

**Comment by lyskouski** [comment] 2024-12-11 07:48
Yeah... something weird has happened
![image](https://github.com/user-attachments/assets/a161ec6a-fefe-48df-8511-d1f6b1bad4b8)

@Igortorrente may you provide some steps to reproduce? I've tried to type conversion and copy-paste it, both times the result (taken in __) was correct.

**Comment by Igortorrente** [comment] 2024-12-11 13:28
[Grabación de pantalla desde 2024-12-11 10-25-22.webm](https://github.com/user-attachments/assets/5c29745f-dc92-4fe7-b511-52eec248a987)

**Comment by lyskouski** [comment] 2024-12-11 13:35
Thanks

**Comment by lyskouski** [comment] 2024-12-11 20:31
If you don't mind, @Igortorrente, I'll detouch that video into a separate thread - https://github.com/lyskouski/app-finance/issues/534 ... by now, cannot reproduce on Windows, Android, and Web versions. Might be relevant to Linux (Flatpak) package

**Comment by Igortorrente** [comment] 2024-12-13 01:18
This is interesting, If I a new credit car in euros, it calculates the values correctly. But if I use a new credit card in PYG, it calculates it wrong. This is a funny bug.

[Grabación de pantalla desde 2024-12-12 22-13-41.webm](https://github.com/user-attachments/assets/23c935b0-b539-424b-b38b-2b253f7793f6)

**Comment by lyskouski** [comment] 2024-12-13 14:25
Thanks @Igortorrente. Assume, that's still on Linux distribution... let me make a blind change (6.0.4) and see it would help.

**Comment by lyskouski** [comment] 2024-12-13 14:33
Hello @Igortorrente, DB is a transaction based model... that provides what was changed by user, meaning that all fixes would be applied without any changes from user side (except situations with conversion rates, since they're a part of transaction history).

**Comment by Igortorrente** [comment] 2024-12-14 02:39
Maybe I'm wrong, but it seems that the conversion rate in the currencies tab is influencing these weird results.

**Closed** 2024-12-17 07:35 UTC
Labels: bug
